apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: broker
spec:
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: wms-ready-application
      sourceRef:
        kind: HelmRepository
        name: c3s-charts
        namespace: flux-system
      version: ">=x.x.x"

  values:
    name: ecde
    webapp:
      image: eccr.ecmwf.int/c3s-applications/ecde-webapp  # image for application
    apiServer:
      image: eccr.ecmwf.int/c3s-applications/ecde-server  # image for application
      env:
        wmsServer: https://cds2-app-cci2.copernicus-climate.eu/c3s-apps/ecde/wms
        rootPath: /c3s-apps/ecde/api
      startupCommand: cp -r ./european_climate_data_explorer/skinnywms/* /skinnywms/ && python3 european_climate_data_explorer/preload_wms.py && make start-server API_HOST=0.0.0.0 ROOT_PATH=$ROOT_PATH
    sharedPvc:
      name: wms-data-volume
      nfsServerUrl: nfs-server.nfs-server.svc.cluster.local
      storage: 10Gi
      storageclass: nfs-csi
      path: /skinnywms
    ingress:
      enable: true
      hostname: cds2-app-cci2.copernicus-climate.eu  
      webappPath: /c3s-apps/ecde/
      apiPath: /c3s-apps/ecde/api/ 
      wmsPath: /c3s-apps/ecde/wms/ 
      secretName: cert-manager-c3s-cert
      ingressclass: nginx-c3s

  interval: 5m0s
  releaseName: broker
