apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
    - name: api-port
      port: {{ .Values.api-service.port }}
      targetPort: {{ .Values.api-service.port }}
