apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-api
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
    - name: api-port
      port: {{ .Values.apiService.port }}
      targetPort: {{ .Values.apiService.port }}
