apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-api
spec:
  replicas: {{ .Values.api-service.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}-api
          image: {{ .Values.api-service.image }}:{{ .Values.api-service.tag }}
          ports:
            - containerPort: {{ .Values.api-service.port }}
          env:
            - name: MODE
              value: {{ .Values.api-service.env.mode }}
            - name: ALLOWED_ORIGIN
              value: {{ .Values.api-service.env.allowed-origin }}:$(WEBAPP_SERVICE_PORT_WEBAPP_PORT)
            - name: WMS_SERVER
              value: {{ .Values.api-service.env.wms-server }}:$(SKINNY_WMS_SERVICE_PORT_WMS_PORT)
            - name: WMS_DATA_DIR
              value: {{ .Values.api-service.env.wms-data-dir }}
            - name: WMS_STYLE_DIR
              value: {{ .Values.api-service.env.wms-style-dir }}
          #   - name: PUBLIC_URL
          #     value: https://ecds-dev.copernicus-climate.eu/c3s-apps/climate-pulse/
        volumeMounts:
        - mountPath: {{ .Values.shared-pvc.path }}
          name: {{ .Values.shared-pvc.name }}
      volumes:
      - name: {{ .Values.shared-pvc.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.shared-pvc.name }}
