apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sharedPvc.name }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.sharedPvc.storage }}
  volumeName: {{ .Values.sharedPvc.pvName }}
  storageClassName: {{ .Values.sharedPvc.storageclass }}
