{{- if .Values.ingress.acme }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-c3s
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: {{ .Values.name }}-solver
spec:
  ingressClassName: {{ .Values.ingress.ingressclass }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.name }}-webapp
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.secretName }}
{{- end}}