apiVersion: v1
kind: Service
metadata:
  name: skinny-wms
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
    - name: wms-port
      port: {{ .Values.skinnyWms.port }}
      targetPort: {{ .Values.skinnyWms.port }}
