apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-webapp
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
    - name: webapp-port
      port: 8080
      targetPort: {{ .Values.webapp.port }}
