# /flux/boot/traefik/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  chart:
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
      version: 2.1.4
  values: {}


  interval: 5m0s
  releaseName: reloader
  targetNamespace: reloader
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
