# Name of application
name: ecde # Name of application
webapp:
  image: eccr.ecmwf.int/c3s-applications/ecde-webapp  # image for application
  tag: latest  # image tag to use (this )
  port: 80  # Port exposed by the application
  replicas: 1
apiService:
  image: eccr.ecmwf.int/c3s-applications/ecde-server  # image for application
  tag: latest  # image tag to use (this )
  port: 5000 # Port exposed by the application
  replicas: 1
  env:
    rootPath: /c3s-apps/ecde/api
    mode: production
    wmsServer: http://ecds-dev-cci2.copernicus-climate.eu/ecde-wms
    wmsDataDir: /skinnywms/appdata
    wmsStyleDir: /skinnywms/styles
skinnyWms:
  image: ecmwf/skinnywms  # image for application
  tag: 0.10.0  # image tag to use (this )
  port: 5000  # Port exposed by the application
  replicas: 0
  env:
    skinnywmsUwsgiWorkers: $(SKINNYWMS_UWSGI_WORKERS:-4)
    skinnywmsDataPath: /skinnywms/appdata
    magicsStylePath: /skinnywms/styles
sharedPvc:
  name: wms-data-volume
  pvName: pv-wms
  storage: 10Gi
  storageclass: nfs-csi
  path: /skinnywms
# Values used for ingress control
ingress:
  enable: true
  # Hostname where the app will be published, this must be mapped to the cluster described by the KUBECONFIG
  hostname: ecds-dev-cci2.copernicus-climate.eu  
  # Path to the application, this must be included in the env when building a JS application
  webappPath: /c3s-apps/ecde/
  apiPath: /c3s-apps/ecde/api/ 
  # SSL certificate secret name:
  secretName: star.copernicus-climate.eu
  ingressclass: nginx-dev
  
