# Name of application
name: windstorm-indicators # Name of application
localDevelopment: false
webapp:
  image: eccr.ecmwf.int/c3s-applications/windstorm-indicators-webapp  # image for application
  tag: latest # image tag to use (this )
  port: 80  # Port exposed by the application
  replicas: 1
apiServer:
  image: eccr.ecmwf.int/c3s-applications/windstorm-indicators-server  # image for application
  tag: latest  # image tag to use (this )
  port: 5000 # Port exposed by the application
  replicas: 1
  env:
    wmsServer: https://cds2-app-cci2.copernicus-climate.eu/c3s-apps/windstorm-indicators/wms
    rootPath: /c3s-apps/windstorm-indicators/api
    mode: production
wms:
  replicas: 0
# Values used for ingress control
ingress:
  enable: true
  # Hostname where the app will be published, this must be mapped to the cluster described by the KUBECONFIG
  hostname: cds2-app-cci2.copernicus-climate.eu 
  # Path to the application, this must be included in the env when building a JS application
  webappPath: /c3s-apps/windstorm-indicators/
  apiPath: /c3s-apps/windstorm-indicators/api/ 
  wmsPath: /c3s-apps/windstorm-indicators/wms/ 
  # SSL certificate secret name:
  secretName: cert-manager-c3s-cert
  ingressclass: nginx-c3s
  certManagerCertificateRequest: false
  certManager:
    clusterIssuer: letsencrypt-c3s # Cluster issuer to use for SSL certificates
    issueTemporaryCertificate: true # Set to true to issue a temporary certificate
