apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      version: 1.17.2

  values:
    crds:
      enabled: true

  interval: 5m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace